# Generated by Django 4.1.7 on 2023-04-26 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppMetrics',
            fields=[
                ('UID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('appID', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=9, max_digits=10)),
                ('appType', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('downloads', models.CharField(max_length=50)),
                ('appIcon', models.CharField(max_length=200)),
                ('overallScore', models.IntegerField()),
                ('thirdPartySharingScore', models.IntegerField()),
                ('shareAdvertisers', models.BooleanField()),
                ('shareLawEnforcement', models.BooleanField()),
                ('shareDataBrokers', models.BooleanField()),
                ('shareHealthCareProvider', models.BooleanField()),
                ('dataEncryptionScore', models.IntegerField()),
                ('encryptedTransit', models.BooleanField()),
                ('encryptedOnDevice', models.BooleanField()),
                ('encryptedMetadata', models.BooleanField()),
                ('sensitiveDataScore', models.IntegerField()),
                ('collectPII', models.BooleanField()),
                ('collectHealthInfo', models.BooleanField()),
                ('collectReproductiveInfo', models.BooleanField()),
                ('collectPeriodCalendarInfo', models.BooleanField()),
                ('transparencyScore', models.IntegerField()),
                ('requestData', models.BooleanField()),
                ('requestDeletion', models.BooleanField()),
                ('controlData', models.BooleanField()),
                ('controlSharing', models.BooleanField()),
            ],
            options={
                'db_table': 'appsMetrics',
            },
        ),
    ]
